//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostBaBy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUser()
        {
            this.tbBlogNews = new HashSet<tbBlogNew>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Citizen_ID { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
        public Nullable<int> AMPHUR_ID { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBlogNew> tbBlogNews { get; set; }
    }
}
